version: '3'
services:
  postgres:
    image: "postgres:14"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "54321:80"
    depends_on:
      - postgres


